### ISSUE TITLE
Line 312-324

### ISSUE THREAD

**Issue by NathanielPhilbrick** [WraithAero/PhantomRocket#1]
The "counter" counting int only reaches >zero once it runs through the if loops once. The command sequence starts at 0,0,0 (the same as null sequence), but the loop for changing command sequence only runs when the command sequence does not = the null sequence so it wont run the do statement

**Comment by ProfessorX404** [comment]
Solved. It should have been <code>while (commandSequence[2] == NULL_SEQUENCE[2] && currentMillis - initMillis < 500);</code>, not <code>while (commandSequence[2] != NULL_SEQUENCE[2] && currentMillis - initMillis < 500);</code>
